#!/bin/bash
./emit_log.rb '0'
./emit_log.rb '1 .'
./emit_log.rb '2 ..'
./emit_log.rb '3 ...'
./emit_log.rb '4 ....'
./emit_log.rb '5 .....'
./emit_log.rb '6 ......'
./emit_log.rb '7 .......'
./emit_log.rb '8 ........'
./emit_log.rb '9 .........'
