#!/bin/bash
./new_task.rb '0'
./new_task.rb '1 .'
./new_task.rb '2 ..'
./new_task.rb '3 ...'
./new_task.rb '4 ....'
./new_task.rb '5 .....'
./new_task.rb '6 ......'
./new_task.rb '7 .......'
./new_task.rb '8 ........'
./new_task.rb '9 .........'
